- uri: template://custom-env
  type: environment
  outputs:
    GITHUB_ORG_ID: ""
    GITHUB_APP_CLIENT_ID: ""
    GITHUB_APP_CLIENT_SECRET: ""
    HUMANITEC_ORG_ID: ""
    HUMANITEC_TOKEN: ""
    CLOUD_PROVIDER: ""
    GITHUB_APP_WEBHOOK_SECRET: ""